// Generated by CoffeeScript 1.3.3
(function() {

  (typeof exports !== "undefined" && exports !== null ? exports : this).render_plot = function(path) {
    return console.log(path);
  };

}).call(this);
